source 'https://rubygems.org'
ruby '2.0.0'

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

gem 'shotgun'

gem 'activesupport', "~>4.1"
gem 'activerecord', "~>4.1"

gem 'rake'

group :test do
  gem 'faker'
  gem 'rspec'
end
